#!/bin/bash
##############################################################################
# BEG: dict impentation
#-----------------------------------------------------------------------------
# dict string defines as following format:
#   "{key1=val1; key2=val 2; key3='val3'; ...}"
#   - the both key & value mustn't include ';' character;
#   - the key mustn't include space(' ') character;
#-----------------------------------------------------------------------------
ATU_MIN_RETRIEVE_ARGC=2
ATU_EMPTY_DICT='{}'
ATU_REPL_SP='!'

ATU_EXPORT_VLIST=()

# get the key's value from dict string.
# param: $1 dict, $2 key
function dict_value
{
    local dict=$1
    local key=$2
    echo $dict | awk -F$key'=' '{print $2}' | awk -F';' '{print $1}'
}

# update the key's value or insert new key to dict.
# param: $1 dict, $2 key=val
function dict_update
{
    local dict=$1
    if [[ $dict == $ATU_EMPTY_DICT ]]; then
        dict=$ATU_EMPTY_DICT
    fi

    local kv=$2
    if [[ $kv =~ .*=.* ]]; then
        # found value need be updated.
        local key=${kv%=*}
        local val=${kv#*=}
        if [[ -z $(dict_value $dict $key) ]]; then
            # append kv
            echo ${dict/\}/$kv;\}}
        else
            echo $dict | sed 's#\('$key'=\)[^;]*;#\1'$val';#'
        fi
    else
        # no value need be updated, remove key.
        if [[ -n $(dict_value $dict $kv) ]]; then
            echo $dict | sed 's#'$kv'[^;]*;##'
        fi
    fi
}

# retrieve the dict, and callback with corresponding key & value.
# param: $1 dict, $2: func_cb
# note: the callback function should treat all rest args from 2nd as value.
function dict_retrieve
{
    local dict=$1
    local func_cb=$2
    [[ ${#@} -lt $ATU_MIN_RETRIEVE_ARGC ]] && return 1
    if [[ $dict != $ATU_EMPTY_DICT ]]; then
        local ckvlist=($(echo $dict | sed 's# *\([{}=;]\) *#\1#g; s# #'$ATU_REPL_SP'#g; s#;#" "#g; s#[{}]#"#g'))
        for ckv in ${ckvlist[@]}; do
            local key=${ckv%=*}
            local val=${ckv#*=}
            $func_cb $key ${val//$ATU_REPL_SP/ }
        done
    fi
}
# END: dict implentation
##############################################################################


##############################################################################
# BEG: log
function __log #$1: tag, $2: content
{
    [[ -z $NDEBUG ]] && echo $*
}

function logi
{
    __log '[INFO]:' $@
}

function loge
{
    __log '[ERROR]:' $@
}

function logw
{
    __log '[WARNING]:' $@
}

function rpt
{
    echo '[REPORT]:' $@
}
# END: log
##############################################################################

# define a variable which need be exported for child-shell used.
# param: variable & value, e.g.: foo=bar
function define
{
    local kv=${@:1}
    if [[ $kv != ${kv%=*} ]]; then
        eval $kv
        eval export ${kv%=*}
        ATU_EXPORT_VLIST=(${ATU_EXPORT_VLIST[@]} ${kv%=*})
    else
        eval $kv=${@:2}
        eval export $kv
        ATU_EXPORT_VLIST=(${ATU_EXPORT_VLIST[@]} $kv)
    fi
}

# undefine a exported variable
# param: $1 undefined key
function undefine
{
    local key=$1
    local index=0
    for k in ${ATU_EXPORT_VLIST[@]}; do
        [[ $k == $key ]] && {
            unset $k
            unset ATU_EXPORT_VLIST[$index]
            break
        }
        index=$((index + 1))
    done
}

# dummy code line for empty block within override function
function __OCCUPY_LINE_DELETE_ME__
{
    printf ""
}
